---

- name: Check for connectivity
  ansible.builtin.ping:
    data: alive

- name: Install required packages
  ansible.builtin.apt:
    pkg:
      - curl
      - gnupg
      - ca-certificates
    state: present

- name: Create keyring directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: Add docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg

- name: Add the repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu   jammy stable
    state: present

- name: Update repository
  ansible.builtin.apt:
    update_cache: true

- name: Install docker
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - python3-pip

- name: Install dockerpy
  ansible.builtin.pip:
    name: "{{ item }}"
  loop:
    - docker
    - docker-compose
