---

- name: Drain MON host
  ceph.automation.ceph_orch_host:
    name: "{{ target_host }}"
    state: drain

- name: Check hosts that get the labels
  ansible.builtin.shell:
    ceph orch host ls --format json | jq -r '.[] | select(.hostname | test("{{ target_host }}")) | .labels[]'
  register: mon_tags

- name: Set fact the tags 
  ansible.builtin.set_fact:
    mon_tag: "{{ mon_tags.stdout_lines }}"

- name: Remove label
  ansible.builtin.command:
    ceph orch host label rm {{ target_host }} {{ service_label }}
  when: 
    - "'_no_conf_keyring' in mon_tag"
    - "'_no_schedule' in mon_tag"  

- name: Pause for draining host
  ansible.builtin.pause:
    seconds: 60

- name: Remove the host
  ceph.automation.ceph_orch_host:
    name: "{{ target_host }}"
    state: absent
  ignore_errors: true
  when: 
    - "'_no_conf_keyring' in mon_tag"
    - "'_no_schedule' in mon_tag"
