---

- name: Read the fetched SSH key into a variable
  ansible.builtin.set_fact:
    ssh_key_content: "{{ lookup('file', './tmp/ceph_ssh.pub') }}"
  tags: add-mgr

- name: Append SSH public key to authorized_keys
  ansible.builtin.lineinfile:
    path: /root/.ssh/authorized_keys
    line: "{{ ssh_key_content }}"
    state: present
    owner: root
    group: root
    mode: '0600'
  tags: add-mgr

- name: Check if the host is already part of the Ceph cluster
  ansible.builtin.shell: |
    ceph orch host ls --format json | jq -r '.[].hostname'
  register: ceph_current_hosts
  delegate_to: "{{ groups['mons'] | first }}"
  run_once: true
  tags: add-mgr

- name: Set fact for whether the host is in the Ceph cluster
  ansible.builtin.set_fact:
    host_in_cluster: "{{ inventory_hostname in ceph_current_hosts.stdout_lines }}"
  tags: add-mgr

- name: Applied MGR host
  ceph.automation.ceph_orch_host:
    name: "{{ inventory_hostname }}"
    labels:
      - mon
      - "{{ service_label }}"
    set_admin_label: true
    state: present
  delegate_to: "{{ groups['mons'] | first }}" 
  when: host_in_cluster
  tags: add-mgr

- name: Applied MGR service
  ceph.automation.ceph_orch_apply:
    spec: |
      service_type: "{{ service_name }}"
      placement:
        label: "{{ service_label }}"
  delegate_to: "{{ groups['mons'] | first }}" 
  tags: add-mgr


################################### DASHBOARD CONFIG #########################


- name: Enabling Dashboard
  ceph.automation.ceph_mgr_module:
    name: dashboard
    state: enable
  delegate_to: "{{ groups['mons'] | first }}" 
  tags: add-mgr

- name: Current Error Status Code
  ceph.automation.ceph_config:
    action: get
    who: "{{ service_name }}"
    option: mgr/dashboard/standby_error_status_code
  register: default_error_code
  delegate_to: "{{ groups['mons'] | first }}"
  tags: add-mgr

- name: Set fact the error status code
  ansible.builtin.set_fact:
    current_error_code: "{{ default_error_code.stdout }}"
  delegate_to: "{{ groups['mons'] | first }}"
  tags: add-mgr

- name: Set new error status code
  ceph.automation.ceph_config:
    action: set
    who: "{{ service_name }}"
    option: mgr/dashboard/standby_error_status_code
    value: 503
  delegate_to: "{{ groups['mons'] | first }}" 
  when: current_error_code != "503"
  tags: add-mgr

################################### BALANCER CONFIG ##########################

# as default the Balancer is on

# set max misplaced for PG from default 5% to 7%

- name: Current Max_Misplaced value
  ceph.automation.ceph_config:
    action: get
    who: "{{ service_name }}"
    option: target_max_misplaced_ratio
  register: default_max_misplaced
  delegate_to: "{{ groups['mons'] | first }}" 
  tags: add-mgr

- name: Set fact default Max_Misplaced
  ansible.builtin.set_fact:
    current_misplaced: "{{ default_max_misplaced.stdout }}"
  delegate_to: "{{ groups['mons'] | first }}"
  tags: add-mgr

- name: Set MGR PGs Max_Misplaced to 7%
  ceph.automation.ceph_config:
    action: set
    who: "{{ service_name }}"
    option: target_max_misplaced_ratio
    value: .07
  delegate_to: "{{ groups['mons'] | first }}" 
  when: current_misplaced != "0.070000"
  tags: add-mgr


# set upmap be the balancer mode

- name: Check default value of balancer mode
  ansible.builtin.shell:
    ceph balancer status | jq -r '.mode'
  register: default_balancer_mode
  delegate_to: "{{ groups['mons'] | first }}"
  tags: add-mgr

- name: Set fact default balancer mode
  ansible.builtin.set_fact:
    current_balancer_mode: "{{ default_balancer_mode.stdout }}"
  delegate_to: "{{ groups['mons'] | first }}"
  tags: add-mgr

- name: Set Balancer mode to upmap
  ansible.builtin.command:
    cmd: ceph balancer mode upmap
  when: current_balancer_mode != "upmap"
  delegate_to: "{{ groups['mons'] | first }}" 
  tags: add-mgr


# set sleep interval for mgr/balancer

- name: Current Sleep interval Value
  ceph.automation.ceph_config:
    action: get
    who: "{{ service_name }}"
    option: mgr/balancer/sleep_interval
  register: default_sleep_interval
  delegate_to: "{{ groups['mons'] | first }}" 
  tags: add-mgr

- name: Set fact default sleep interval
  ansible.builtin.set_fact:
    current_sleep_interval: "{{ default_balancer_mode.stdout }}"
  delegate_to: "{{ groups['mons'] | first }}"
  tags: add-mgr

- name: Set new Sleep interval value
  ceph.automation.ceph_config:
    action: set
    who: "{{ service_name }}"
    option: mgr/balancer/sleep_interval
    value: "{{ sleep_time }}"
  delegate_to: "{{ groups['mons'] | first }}"
  tags: add-mgr


################################### PG_AUTOSCALER CONFIG #####################


- name: Ensure the autoscaling be on for all pools
  ansible.builtin.command:
    cmd: ceph config set osd osd_pool_default_pg_autoscale_mode on
  delegate_to: "{{ groups['mons'] | first }}" 
  tags: add-mgr

- name: Current PG per Pools value
  ansible.builtin.shell:
    ceph config get mon mon_target_pg_per_osd
  register: default_pg_pool
  delegate_to: "{{ groups['mons'] | first }}"
  tags: add-mgr

- name: Set fact the PG per Pools
  ansible.builtin.set_fact:
    current_pg_pool: "{{ default_pg_pool.stdout }}"
  delegate_to: "{{ groups['mons'] | first }}"
  tags: add-mgr

- name: Set PG per Pool new value
  ceph.automation.ceph_config:
    action: set
    who: global
    option: mon_target_pg_per_osd
    value: "{{ desire_pg_pool }}"
  delegate_to: "{{ groups['mons'] | first }}"
  tags: add-mgr
