---

- name: Include remove service tasks if target_action is 'service'
  ansible.builtin.include_tasks: remove_service.yml
  when: target_action == "service"

- name: Include remove host tasks if target_action is 'host'
  ansible.builtin.include_tasks: remove_host.yml
  when: target_action == "host"
  