---

- name: Check for connectivity
  ansible.builtin.ping:
    data: alive

- name: Initial CEPH Cluster
  ceph.automation.cephadm_bootstrap:
    mon_ip: "{{ ansible_facts['eth1']['ipv4']['address'] }}"
    cluster_network: "{{ ansible_facts['eth1']['ipv4']['network'] }}/{{ ansible_facts['eth1']['ipv4']['prefix'] }}"
    initial_dashboard_user: "{{ dashboard_user }}"
    initial_dashboard_password: "{{ dashboard_password }}"
  register: cephadm_bootstrap

- name: Cephadm bootstrap result
  ansible.builtin.debug:
    var: cephadm_bootstrap.stdout

- name: Set MON public network
  ceph.automation.ceph_config:
    action: set
    who: mon
    option: public_network
    value: "{{ ansible_facts['eth1']['ipv4']['network'] }}/{{ ansible_facts['eth1']['ipv4']['prefix'] }}"


- name: Read the Ceph public key
  ansible.builtin.slurp:
    src: /etc/ceph/ceph.pub
  register: ceph_pub_key
  run_once: true

- name: Decode and store the Ceph public key in a variable
  ansible.builtin.set_fact:
    ceph_ssh_pub: "{{ ceph_pub_key.content | b64decode }}"
  run_once: true

- name: Fetch ssh pub key file
  ansible.builtin.fetch:
    src: "/etc/ceph/ceph.pub"
    dest: "tmp/ceph_ssh.pub"
    flat: true
  delegate_to: "{{ groups['mons'] | first }}"
